language: generic 
sudo: required
services:
  - docker

before_install:
- docker build -t maximam2014/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true maximam2014/react-test npm test

after_success:
  - docker build -t maximam2014/multi-client ./client
  - docker build -t maximam2014/multi-nginx ./nginx
  - docker build -t maximam2014/multi-server ./server
  - docker build -t maximam2014/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take these images and push them to docker hub
  - docker push maximam2014/multi-client
  - docker push maximam2014/multi-nginx
  - docker push maximam2014/multi-server
  - docker push maximam2014/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-908841334002
  buket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY